name: Flutter Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # update checkout too

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'   # latest stable

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4   # updated to v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
